# .streamlit/secrets.toml (TEMPLATE - do NOT store real secrets in public repo)

[GEMINI]
api_key = "YOUR_GEMINI_API_KEY"

[RAZORPAY]
key_id = "YOUR_RAZORPAY_KEY_ID"
key_secret = "YOUR_RAZORPAY_KEY_SECRET"

[SENDGRID]
api_key = "YOUR_SENDGRID_API_KEY"

# Firebase service account JSON as a single-line string (or use Cloud Run service account)
# Example: st.secrets["FIREBASE_SERVICE_ACCOUNT_JSON"] should contain the JSON contents of the service account key.
FIREBASE_SERVICE_ACCOUNT_JSON = """
{
  "type": "service_account",
  "project_id": "your-project-id",
  ...
}
"""

[firebase]
# Optional firebase fields for client SDK (useful if you later implement client-side login)
apiKey = "YOUR_FIREBASE_API_KEY"
authDomain = "YOUR_FIREBASE_AUTH_DOMAIN"
projectId = "YOUR_FIREBASE_PROJECT_ID"
storageBucket = "YOUR_FIREBASE_BUCKET"
messagingSenderId = "YOUR_FIREBASE_MESSAGING_ID"
appId = "YOUR_FIREBASE_APP_ID"

[ADMIN]
# list admin emails who can access Admin dashboard in the app
emails = ["you@taicc.co"]
