# .streamlit/secrets.toml (TEMPLATE - do NOT store real secrets in public repo)

[GEMINI]
api_key = "AIzaSyDr8kniG72w3zBaYGjZs1wWJ4LZc5hZQAo"

[RAZORPAY]
key_id = "YOUR_RAZORPAY_KEY_ID"
key_secret = "YOUR_RAZORPAY_KEY_SECRET"

[SENDGRID]
api_key = "YOUR_SENDGRID_API_KEY"

[google_drive]
credentials_json = "824973653935-761b9agse4ej2ftbraqo01j6ob30cog9.apps.googleusercontent.com"

[firebase]
# Optional firebase fields for client SDK (useful if you later implement client-side login)
apiKey: "AIzaSyAr6n29ryxLr-njqfqXlwcax6QHQH5gIk0",
authDomain: "ai-readiness-assessment-1c84b.firebaseapp.com",
projectId: "ai-readiness-assessment-1c84b",
storageBucket: "ai-readiness-assessment-1c84b.firebasestorage.app",
messagingSenderId: "1077396153969",
appId: "1:1077396153969:web:8825b804f63e932e549dd0",
measurementId: "G-1N001M7PGP"

[ADMIN]
# list admin emails who can access Admin dashboard in the app
emails = ["taiccpartners@gmail.com"]
